[package]
name = "git-prompt"
version = "0.1.0"
edition = "2024"

[dependencies]
compact_str = "0.9"
git2 = { version = "0.20", default-features = false }

[profile.release]
lto = true
codegen-units = 1
